version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/code
      - /code/models/
    ports:
      - "8000:8000"
    depends_on:
      - db