version: '3'

services:
  db:
    image: postgres
  api:
    build: ./api
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - api